version: '3.7'

services:
  dependency-track:
    image: dependencytrack/bundled:latest
    container_name: dependency-track
    ports:
      - "9090:8080"
    environment:
      - ALPINE_DATABASE_PASSWORD=password
      - ALPINE_DATABASE_USER=admin
    volumes:
      - dependency-track-data:/data
    networks:
      - dev-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9091:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - dev-network

volumes:
  dependency-track-data:
  jenkins-data:

networks:
  dev-network:
